local Flux = loadstring(game:HttpGet"https://pastebin.com/raw/4TdpZMan")()

local win = Flux:Window("Haahaa Hub", "Game Name", Color3.fromRGB(255, 138, 225), Enum.KeyCode.RightShift)
local tab = win:Tab("Tab 1", "http://www.roblox.com/asset/?id=6023426915")
tab:Button("Button", "This is just a button", function()
Flux:Notification("You clicked the Button!", "OK")
end)
tab:Label("This is just a text")
tab:Line()
tab:Toggle("Toggle Button", "This is just a toggle button!", function(t)
print(t)
end)
tab:Slider("Slider", "This is just a slider!", 0, 100,16,function(t)
print(t)
end)
tab:Dropdown("Dropdown", {"Item1","Item2","Item3"}, function(t)
print(t)
end)
tab:Colorpicker("Colorpicker", Color3.fromRGB(255,1,1), function(t)
print(t)
end)
tab:Textbox("Input Textbox", "This is just a textbox", true, function(t)
print(t)
end)
tab:Bind("Bind", Enum.KeyCode.Q, function()
print("This is just a bind!")
end)
win:Tab("Tab 2", "http://www.roblox.com/asset/?id=6022668888")
